# Snapshot report for `packages/build/tests/error/plugin_load/tests.js`

The actual snapshot is saved in `tests.js.snap`.

Generated by [AVA](https://ava.li).

## Early exit

> Snapshot 1

    `␊
    ┌─────────────────────────────┐␊
    │        Netlify Build        │␊
    └─────────────────────────────┘␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      repositoryRoot: /file/path␊
    ␊
    > Current directory␊
      /file/path␊
    ␊
    > Config file␊
      /file/path␊
    ␊
    > Resolved config␊
      plugins:␊
        - package: /file/path␊
        - package: /file/path␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - /file/path␊
       - /file/path␊
    ␊
    ┌─────────────────────────────────────┐␊
    │ 1. onPreBuild command from /file/path │␊
    └─────────────────────────────────────┘␊
    ␊
    onPreBuild␊
    ␊
    (/file/path onPreBuild completed in 1ms)␊
    ␊
    ┌───────────────────────────────────────┐␊
    │ 2. onBuild command from /file/path │␊
    └───────────────────────────────────────┘␊
    ␊
    onBuild start␊
    onBuild end␊
    ␊
    (/file/path onBuild completed in 1ms)␊
    ␊
    ┌──────────────────────────────────────┐␊
    │ 3. onPostBuild command from /file/path │␊
    └──────────────────────────────────────┘␊
    ␊
    ␊
    ┌──────────────────────────────────┐␊
    │ Plugin "/file/path" internal error │␊
    └──────────────────────────────────┘␊
    ␊
      Error message␊
      Could not receive event from child process because it already exited.␊
      The plugin might have exited due to a bug terminating the process, such as an infinite loop.␊
      The plugin might also have explicitly terminated the process, for example with process.exit().␊
      Plugin methods should instead:␊
        - on success: return␊
        - on failure: call utils.build.failPlugin() or utils.build.failBuild()␊
    ␊
      Plugin details␊
      ID:             /file/path␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      npm link:       https://www.npmjs.com/package/@netlify/build␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPostBuild" event in local plugin "/file/path"␊
    `

## Exits in plugins

> Snapshot 1

    `␊
    ┌─────────────────────────────┐␊
    │        Netlify Build        │␊
    └─────────────────────────────┘␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      repositoryRoot: /file/path␊
    ␊
    > Current directory␊
      /file/path␊
    ␊
    > Config file␊
      /file/path␊
    ␊
    > Resolved config␊
      plugins:␊
        - package: /file/path␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - /file/path␊
    ␊
    ┌─────────────────────────────────┐␊
    │ 1. onInit command from /file/path │␊
    └─────────────────────────────────┘␊
    ␊
    ␊
    ┌──────────────────────────────────┐␊
    │ Plugin "/file/path" internal error │␊
    └──────────────────────────────────┘␊
    ␊
      Error message␊
      Plugin exited with exit code 1 and signal null.␊
      The plugin might have exited due to a bug terminating the process, such as an infinite loop.␊
      The plugin might also have explicitly terminated the process, for example with process.exit().␊
      Plugin methods should instead:␊
        - on success: return␊
        - on failure: call utils.build.failPlugin() or utils.build.failBuild()␊
    ␊
      Plugin details␊
      ID:             /file/path␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      npm link:       https://www.npmjs.com/package/@netlify/build␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onInit" event in local plugin "/file/path"␊
    `

## No repository root

> Snapshot 1

    `␊
    ┌─────────────────────────────┐␊
    │        Netlify Build        │␊
    └─────────────────────────────┘␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      repositoryRoot: /file/path␊
    ␊
    > Current directory␊
      /file/path␊
    ␊
    > Config file␊
      /file/path␊
    ␊
    > Resolved config␊
      plugins:␊
        - package: /file/path␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - /file/path␊
    ␊
    ┌────────────────────────────────────┐␊
    │ 1. onInit command from /file/path │␊
    └────────────────────────────────────┘␊
    ␊
    ␊
    ┌─────────────────────────────────────┐␊
    │ Plugin "/file/path" internal error │␊
    └─────────────────────────────────────┘␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Error location␊
      In "onInit" event in local plugin "/file/path"␊
    STACK TRACE␊
    `

## Node module all fields

> Snapshot 1

    `␊
    ┌─────────────────────────────┐␊
    │        Netlify Build        │␊
    └─────────────────────────────┘␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      repositoryRoot: /file/path␊
    ␊
    > Current directory␊
      /file/path␊
    ␊
    > Config file␊
      /file/path␊
    ␊
    > Resolved config␊
      plugins:␊
        - package: netlify-plugin-test␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - netlify-plugin-test@1.0.0␊
    ␊
    ┌────────────────────────────────────────────┐␊
    │ 1. onInit command from netlify-plugin-test │␊
    └────────────────────────────────────────────┘␊
    ␊
    ␊
    ┌─────────────────────────────┐␊
    │        Build failed         │␊
    └─────────────────────────────┘␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      ID:             netlify-plugin-test␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/test/test.git␊
      npm link:       https://www.npmjs.com/package/netlify-plugin-test␊
      Report issues:  https://test.com/test␊
    ␊
      Error location␊
      In "onInit" event in npm package "netlify-plugin-test"␊
    STACK TRACE␊
    `

## Node module partial fields

> Snapshot 1

    `␊
    ┌─────────────────────────────┐␊
    │        Netlify Build        │␊
    └─────────────────────────────┘␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      repositoryRoot: /file/path␊
    ␊
    > Current directory␊
      /file/path␊
    ␊
    > Config file␊
      /file/path␊
    ␊
    > Resolved config␊
      plugins:␊
        - package: netlify-plugin-test␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - netlify-plugin-test@␊
    ␊
    ┌────────────────────────────────────────────┐␊
    │ 1. onInit command from netlify-plugin-test │␊
    └────────────────────────────────────────────┘␊
    ␊
    ␊
    ┌─────────────────────────────┐␊
    │        Build failed         │␊
    └─────────────────────────────┘␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      ID:             netlify-plugin-test␊
    ␊
      Error location␊
      In "onInit" event in npm package "netlify-plugin-test"␊
    STACK TRACE␊
    `

## Process warnings

> Snapshot 1

    `␊
    ┌─────────────────────────────┐␊
    │        Netlify Build        │␊
    └─────────────────────────────┘␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      repositoryRoot: /file/path␊
    ␊
    > Current directory␊
      /file/path␊
    ␊
    > Config file␊
      /file/path␊
    ␊
    > Resolved config␊
      plugins:␊
        - package: /file/path␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - /file/path␊
    ␊
    ┌─────────────────────────────────┐␊
    │ 1. onInit command from /file/path │␊
    └─────────────────────────────────┘␊
    ␊
    onInit␊
    ␊
    (/file/path onInit completed in 1ms)␊
    ␊
    ┌─────────────────────────────┐␊
    │   Netlify Build Complete    │␊
    └─────────────────────────────┘␊
    ␊
    (Netlify Build completed in 1ms)␊
    ␊
     ‼  warning (Warning)  test␊
    STACK TRACE␊
    STACK TRACE`

## Top function errors local

> Snapshot 1

    `␊
    ┌─────────────────────────────┐␊
    │        Netlify Build        │␊
    └─────────────────────────────┘␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      repositoryRoot: /file/path␊
    ␊
    > Current directory␊
      /file/path␊
    ␊
    > Config file␊
      /file/path␊
    ␊
    > Resolved config␊
      plugins:␊
        - package: /file/path␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
    ␊
    ┌──────────────────────────────────┐␊
    │ Plugin "/file/path" internal error │␊
    └──────────────────────────────────┘␊
    ␊
      Error message␊
      Error: Could not load plugin:␊
      test␊
    ␊
      Plugin details␊
      ID:             /file/path␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      npm link:       https://www.npmjs.com/package/@netlify/build␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      While loading local plugin "/file/path"␊
    STACK TRACE␊
    `

## Top-level errors

> Snapshot 1

    `␊
    ┌─────────────────────────────┐␊
    │        Netlify Build        │␊
    └─────────────────────────────┘␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      repositoryRoot: /file/path␊
    ␊
    > Current directory␊
      /file/path␊
    ␊
    > Config file␊
      /file/path␊
    ␊
    > Resolved config␊
      plugins:␊
        - package: /file/path␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
    ␊
    ┌──────────────────────────────────┐␊
    │ Plugin "/file/path" internal error │␊
    └──────────────────────────────────┘␊
    ␊
      Error message␊
      Error: Could not import plugin:␊
      test␊
    ␊
      Plugin details␊
      ID:             /file/path␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      npm link:       https://www.npmjs.com/package/@netlify/build␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      While loading local plugin "/file/path"␊
    STACK TRACE␊
    `

## Uncaught exception

> Snapshot 1

    `␊
    ┌─────────────────────────────┐␊
    │        Netlify Build        │␊
    └─────────────────────────────┘␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      repositoryRoot: /file/path␊
    ␊
    > Current directory␊
      /file/path␊
    ␊
    > Config file␊
      /file/path␊
    ␊
    > Resolved config␊
      plugins:␊
        - package: /file/path␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - /file/path␊
    ␊
    ┌─────────────────────────────────┐␊
    │ 1. onInit command from /file/path │␊
    └─────────────────────────────────┘␊
    ␊
    ␊
    ┌──────────────────────────────────┐␊
    │ Plugin "/file/path" internal error │␊
    └──────────────────────────────────┘␊
    ␊
      Error message␊
      UncaughtException: an exception was thrown but not caught: Error: test␊
    ␊
      Plugin details␊
      ID:             /file/path␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      npm link:       https://www.npmjs.com/package/@netlify/build␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onInit" event in local plugin "/file/path"␊
    STACK TRACE␊
    `

## Unhandled promises

> Snapshot 1

    `␊
    ┌─────────────────────────────┐␊
    │        Netlify Build        │␊
    └─────────────────────────────┘␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      repositoryRoot: /file/path␊
    ␊
    > Current directory␊
      /file/path␊
    ␊
    > Config file␊
      /file/path␊
    ␊
    > Resolved config␊
      plugins:␊
        - package: /file/path␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - /file/path␊
    ␊
    ┌─────────────────────────────────┐␊
    │ 1. onInit command from /file/path │␊
    └─────────────────────────────────┘␊
    ␊
    onInit␊
    ␊
    ┌──────────────────────────────────┐␊
    │ Plugin "/file/path" internal error │␊
    └──────────────────────────────────┘␊
    ␊
      Error message␊
      UnhandledRejection: a promise was rejected but not handled: Error: test␊
    ␊
      Plugin details␊
      ID:             /file/path␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      npm link:       https://www.npmjs.com/package/@netlify/build␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onInit" event in local plugin "/file/path"␊
    STACK TRACE␊
    `
