const throwError = function() {
  throw new Error('test')
}

throwError()
